
# ~/nk

[nk.assets]
path='.assets'
icon='folder-tar'

[nk.secrets]
path='.secrets'
icon='folder-locked'

[nk.git]
path='.git'
icon='folder-git'

[nk.logs]
path='.logs'
icon='folder-log'

[nk.vscode]
path='.vscode'
icon='folder-extension'

[nk.gits]
path='Gits'
icon='folder-download'

# Some personal dirs
[nk.PersonalDirs.lobby]
path='Lobby'
icon='folder-open'
[nk.PersonalDirs.cuwo]
path='CuWo'
icon='folder-presentation'
[nk.PersonalDirs.desk]
path='Desk'
icon='folder-desktop'
[nk.PersonalDirs.engg]
path='Engg'
icon='folder-design'
[nk.PersonalDirs.pbco]
path='Pbco'
icon='folder-library'
[nk.PersonalDirs.psco]
path='Psco'
icon='folder-library'
[nk.PersonalDirs.sbco]
path='Sbco'
icon='folder-library'
[nk.PersonalDirs.bored]
path='Bored'
icon='folder-temp'
[nk.PersonalDirs.things]
path='Things'
icon='folder-table'
[nk.PersonalDirs.things-books]
path='Things/Books'
icon='folder-book'

# nk/Dev

[nk-Dev.bin]
path='bin'
icon='folder-appimage'

[nk-Dev.envs]
path='Envs'
icon='folder-script'

# nk/Notes

[nk-Notes.bin]
path='bin'
icon='folder-appimage'

# ~

[home.tasks]
path='Tasks'
icon='folder-notes'

[home.vaults]
path='Vaults'
icon='folder-decrypted'

# $XDG_CONFIG_HOME/user-dirs.dirs
[home.XDG.UserDirs]
# XDG_DESKTOP_DIR="$HOME/Desktop"
desktop.path='Desktop'
# XDG_DOWNLOAD_DIR="$HOME/Downloads"
download.path='Downloads'
# XDG_MUSIC_DIR="$HOME/Music"
music.path='Music'
# XDG_DOCUMENTS_DIR="$HOME/Documents"
documents.path='Documents'
# XDG_PICTURES_DIR="$HOME/Pictures"
pictures.path='Pictures'
# XDG_VIDEOS_DIR="$HOME/Videos"
videos.path='Videos'
# XDG_TEMPLATES_DIR="$HOME/Templates"
templates.path='Templates'
# XDG_PUBLICSHARE_DIR="$HOME/Public"
publicshare.path='Public'
#
# dolphin shows icons by default
# https://wiki.archlinux.org/title/XDG_user_directories

[home.XDG.BaseDirs]
# XDG_CONFIG_HOME
#     Where user-specific configurations should be written (analogous to /etc).
#     Should default to $HOME/.config.
config.path='.config'
# XDG_CACHE_HOME
#     Where user-specific non-essential (cached) data should be written (analogous to /var/cache).
#     Should default to $HOME/.cache.
cache.path='.cache'
# XDG_DATA_HOME
#     Where user-specific data files should be written (analogous to /usr/share).
#     Should default to $HOME/.local/share.
data.path='.local/share'
# XDG_STATE_HOME
#     Where user-specific state files should be written (analogous to /var/lib).
#     Should default to $HOME/.local/state.
state.path='.local/state'
# XDG_RUNTIME_DIR
#     Used for non-essential, user-specific data files such as sockets, named pipes, etc.
#pam_systemd creates and sets this each time.
# XDG_DATA_DIRS
#     List of directories separated by : (analogous to PATH).
#     Should default to /usr/local/share:/usr/share.
#not writeable anyway
# XDG_CONFIG_DIRS
#     List of directories separated by : (analogous to PATH).
#     Should default to /etc/xdg.
#not writeable anyway
# Others (not in specifications)
_local.path='.local'
_local-bin.path='.local/bin'
_local-lib.path='.local/lib'
#
# yet to decide icons
# https://wiki.archlinux.org/title/XDG_Base_Directory
# https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

[home.DotDirs]
flatpak.app_data.path='.var'
flatpak.app_data.icon='folder-flatpak'
# add some later
