
# ~/nk

[nk.assets]
path='.assets'
icon='folder-tar'

[nk.secrets]
path='.secrets'
icon='folder-locked'

[nk.git]
path='.git'
icon='folder-git'

[nk.logs]
path='.logs'
icon='folder-log'

[nk.vscode]
path='.vscode'
icon='folder-extension'

[nk.gits]
path='Gits'
icon='folder-download'

# Some personal dirs
[nk.Personal.Lobby]
path='Lobby'
icon='folder-open'
[nk.Personal.CuWo]
path='CuWo'
icon='folder-presentation'
[nk.Personal.Desk]
path='Desk'
icon='folder-desktop'
[nk.Personal.Engg]
path='Engg'
icon='folder-design'
[nk.Personal.Pbco]
path='Pbco'
icon='folder-library'
[nk.Personal.Psco]
path='Psco'
icon='folder-library'
[nk.Personal.Sbco]
path='Sbco'
icon='folder-library'
[nk.Personal.Bored]
path='Bored'
icon='folder-temp'
[nk.Personal.Things]
path='Things'
icon='folder-table'
[nk.Personal.ThingsBooks]
path='Things/Books'
icon='folder-book'

# Others ~/nk/Setup
[nk.GIL1]
dm.path='.dm'
dm.icon='folder-comic'
id.path='.id'
id.icon='folder-root'
Fixes.path='Fixes'
Fixes.icon='folder-script'

# ~

[home.tasks]
path='Tasks'
icon='folder-notes'

[home.vaults]
path='Vaults'
icon='folder-decrypted'
